<h1>New task</h1>
<form class="form-horizontal" action="<?= $this->url('task', ['action' => 'store']) ?>" method="POST">
    <input class="form-control" type="text" name="title" minlength="3" maxlength="50" value="" placeholder="Title..." required>
    <textarea class="form-control" name="description" minlength="5" maxlength="100" placeholder="Description..."></textarea>
    <button type="submit" class="btn">Send</button>
</form>