<h1>Update task</h1>
<form class="form-horizontal form-meister" action="<?= $this->url('task', ['action' => 'update', 'id' => $task->id]) ?>" method="POST">
    <input class="form-control" type="hidden" name="id" value="<?= $task->id ?>">
    <input class="form-control" type="text" name="title" minlength="3" maxlength="50" value="<?= $task->title ?>" required>
    <select class="form-control" name="status" required>
        <option value="0" <?= ($task->status == 0) ? 'selected' : '' ?>>PENDING</option>
        <option value="1" <?= ($task->status == 1) ? 'selected' : '' ?>>COMPLETE</option>
    </select>
    <textarea class="form-control" name="description" minlength="5" maxlength="100" placeholder="Description..."><?= $task->description ?></textarea>
    
    <a href="<?= $this->url('task') ?>" class="btn btn-meister danger">Cancel</a>
    <button type="submit" class="btn btn-meister">Update</button>
</form>